### ISSUE TITLE
Unable to run container with the given image for json-lint

### ISSUE THREAD

**Issue by gowthaman-new** [miy4/docker-json-schema-validator#1]
Hey,
I have created docker image as per your dockerfile. When running container, it throws below error message. Can you please help to fix it.

Error: Could not find or load main class com.github.fge.jsonschema.main.cli.Main

**Comment by miy4** [comment]
Hi gowthaman-new,
It works well in my environment. `docker build` and `docker pull` are both okay.
Could you tell me steps (and results) of how you built and run?
